import './globals.css'
import Header from "./(components)/Header/Header"


export const metadata = {
  title: 'Evolve Ai',
  description: 'Generated by Adan Atif',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='c'>
        <Header/>
        {children}
        {/* <Footer/> */}
        </body>
    </html>
  )
}
